### ISSUE TITLE
drawing of pedigrees

### ISSUE THREAD

**Issue by romunov** [romunov/wolfexplorer#17]
Draw a pedigree for the selection. Perhaps in the sidebar under sliders, or perhaps a new menu/tab. This is up for discussion. Probably worth a bit of experimenting.

**Comment by zkuralt** [comment]
Package kinship2 is definitely the first option, but in order to create interactive pedigree plot it would be good to look at other packages as well.

**Comment by romunov** [comment]
Solved by pull request #39
