### ISSUE TITLE
implement selection by cluster

### ISSUE THREAD

**Issue by romunov** [romunov/wolfexplorer#6]
Add filter which selects based on clusters designated in parentage.

**Comment by zkuralt** [comment]
Maybe a new column indicating the cluster of the animal could be added to the samples table, when parentage file is uploaded. We would just need to extract cluster info of an animal (if available) from parentage table.

**Comment by romunov** [comment]
This information is known only after the pedigree analysis has been performed. If we go your way, we could make a default for everyone to be in group 1 and if there are more than 1 groups, we display selection of group/cluster. What happens when parentage data is added? And it possibly differs from groups made by samples data?
